### ISSUE TITLE
English instead of German in ucp

### ISSUE THREAD

**Issue by D-MBLD** [D-MBLD/phpbb-telegram-bridge#1]
The description for telegram id in UCP appears in English, even if user language is German.

**Comment by ReXt0r** [comment]
`'TELEGRAM_ID_DESCR'` ?
Strangely, for my localization (created on the basis of EN), the value is displayed as expected.
![2023-02-19_19-35-35](https://user-images.githubusercontent.com/123004533/219942831-f44dba40-46df-4dec-91a3-77d7f6575aa7.png)

**Comment by ReXt0r** [comment]
Files `info_ucp_telegram.php` and `info_acp_telegram.php` are missing in DE-localization. Isn't that the point? :)

**Comment by D-MBLD** [comment]
Have not seen your comments. Yes you are right. info_ucp_telegram.php is missing in DE.
(Also info_acp_telegram.php, but for admins, I don't think it is that important)

**Comment by D-MBLD** [comment]
Fixed with https://github.com/D-MBLD/phpbb-telegram-bridge/commit/373d04618962fe97bade3a1506e2c07f45397738
